#!/bin/bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
nomadDir="$( dirname $scriptDir)"
nomadDir="$( dirname $nomadDir)"
nomadDir="$( dirname $nomadDir)"

cd $scriptDir
#make clean
make test

cd $nomadDir
for file in `find test -mindepth 2 -type f`
do
  $file
done
